name: vprofile deploy
on: workflow_dispatch
env:
    AWS_REGION: us-west-1
    ECR_REPOSITORY: vprofileapp
    EKS_CLUSTER: vprofile-eks

jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
            - name: Code checkout
              uses: actions/checkout@v4

            - name: Maven test
              run: mvn test

            - name: Checkstyle
              run: mvn checkstyle:checkstyle

            - name: Set Java 11
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: 11

            # Setup sonar-scanner
            - name: Set up SonarQube
              uses: warchant/setup-sonar-scanner@v7

            - name: SonarQube Scan
              run: sonar-scanner
                    -Dsonar.host.url=${{ secrets.SONAR_URL }}
                    -Dsonar.login=${{ secrets.SONAR_TOKEN }}
                    -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
                    -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
                    -Dsonar.sources=src/
                    -Dsonar.junit.reportsPath=target/surefire-reports/ 
                    -Dsonar.jacoco.reportsPath=target/jacoco.exec 
                    -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
                    -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/  

            - name: SonarQube quality gate check
              id: sonarqube-quality-gate
              uses: sonarsource/sonarqube-quality-gate-action@master
              # Force timeout
              timeout-minutes: 5
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST: ${{ secrets.SONAR_URL }}